name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
      fail-fast: false

    steps:
    - name: "Get OS version (Linux)"
      if: startsWith(runner.os, 'Linux')
      run: |
        echo "OS_VERSION=`lsb_release -sr`" >> $GITHUB_ENV
        echo "PIP_DEFAULT_CACHE=$HOME/.cache/pip" >> $GITHUB_ENV
        echo "DEFAULT_HOME=$HOME" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Restore pip cache"
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_DEFAULT_CACHE }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/python/requirements.txt') }}-v1
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install and test
      run: |
        pip install -U -r python/requirements.txt dask[dataframe] distributed
        cd python
        python setup.py develop test

